-- ============================================================
-- READINESS CHECK (read-only) — GENERATED by scripts/deploy/gen-dev-check.js; do not edit.
-- inputs-sha256: c16db99f4dd9b6bc7a301c8bad0c096df88badee7aab894402ede72b876c291f
-- Run on the instance to check (dev): pgAdmin Query Tool, Execute (F5). Result:
--   part · item · status (OK / MISSING / OUTDATED / EXTRA / INFO) · detail · action
-- The first rows (part 'summary') say which SQL files / field scripts to run and
-- which JS blocks to re-paste. Read-only: it only fills session TEMP tables
-- (gone when the tab closes); no table of the database is written.
-- ============================================================
DROP TABLE IF EXISTS pg_temp._check;
DROP TABLE IF EXISTS pg_temp._exp_fn;
DROP TABLE IF EXISTS pg_temp._exp_trg;
DROP TABLE IF EXISTS pg_temp._exp_obj;
DROP TABLE IF EXISTS pg_temp._exp_field;
DROP TABLE IF EXISTS pg_temp._exp_js;
CREATE TEMP TABLE _check (section int, part text, item text, status text, detail text, action text);

CREATE TEMP TABLE _exp_fn (name text, args text, md5 text, file text);
INSERT INTO _exp_fn VALUES
  ('by_case_activate_payment_request_if_ready', 'p_payment_request_id bigint', 'd53412fa3773104657b4ee1b50aab94f', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_case_done_activates_payment_request', '', '22081dba9d86d5448e24b466adc34036', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_create_scheduled_payment_requests', '', '049c2eec402156cd9143e6cf6da4b891', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_due_date_activates_payment_request', '', 'c99ef32ba33417876acebf107d6ee448', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_one_time_case_linked_creates_payment_request', '', '8c322d3aa990ab8c8d285ab206beafcc', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_case_one_time_ensure_payment_request', 'p_contract_id bigint, p_case_status text', 'def2c40cf6dae28de5f290d9a97fb8b3', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_case_one_time_sync_trigger_mode', 'p_payment_request_id bigint', '85b0409b1ee0af50e83ddf7c6b3d5ff9', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_schedule_row_creates_payment_request', '', 'f76aef072b058f93a5af0c5213cdbd45', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_case_schedule_tag_copies_to_payment_request', '', 'f15203996c3b869c1ee6c21941bcd4c0', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_case_task_deleted_rechecks_payment_request', '', '11020af957efc23467fb312224a52252', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_task_done_activates_payment_request', '', 'a1f7f523aed2ed351b297c2727c4e433', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_case_task_linked_activates_payment_request', '', 'c57cc5f21dafab21c205b98b278553f4', 'pgsql/by_case_payment_request_automation.sql'),
  ('by_service_check_and_create_payment_request', 'p_project_service_id bigint', 'fa252ee1f60cf9de945bba893c8bd4d7', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_combo_check_for_service', 'p_project_service_id bigint', '02a60ae35ef242938cad973130eab4e4', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_combo_item_check_and_create', 'p_schedule_id bigint', '02d37a0091d9c22765d903f3e0038f9f', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_contract_linked_catches_up_done_tasks', '', '6055006af4a21befc7b73819bb30ded2', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_package_allocated_amount', 'p_project_service_id bigint', '760e920e7c0da017dffb6c561969e18e', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_service_amount', 'p_project_service_id bigint', 'f579a793b89d8f9b55f73d8699d7c1af', 'pgsql/unified_contract_payment_schedule.sql'),
  ('by_service_task_group_done_creates_payment_request', '', '9d531cb3a627ddcc1a3acb2eb1eba579', 'pgsql/unified_contract_payment_schedule.sql'),
  ('cascade_payment_status_to_case', '', 'ef8cea5b93e74140eb33554ea04200a3', 'pgsql/contract_payment_status_workflow.sql'),
  ('case_auto_complete_when_tasks_done', '', '65b674fdb3847eaced563eca60529cd2', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_billing_plan_init_retainer_state', '', 'ea4cab7fc68ea5ed28218e1f3f28e848', 'pgsql/contract_billing_plans_trigger.sql'),
  ('contract_init_outstanding', '', '7c1eaeb628e06d57eedeee6446556572', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_recompute_outstanding', '', '48bd3e5364514c8e2ab6efdfcb06ecd1', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_recompute_outstanding_for', 'p_contract_id bigint', '77fe2193e31cc3882672df55266430e6', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_resolved_total', 'p_contract_id bigint', 'ca342119b69a16071755c4b47f17a65e', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_resolved_total_from_row', 'c contracts', '6ed5ad87041ba42b003ba04155bd2e34', 'pgsql/contract_payment_status_workflow.sql'),
  ('contract_retainer_value', 'p_contract_id bigint', '913035077a5aa11ed43565da0f59351d', 'pgsql/contract_payment_status_workflow.sql'),
  ('currency_catalog_fix_run', '', '6ab3878ae464ace122d0a2804e368dd7', 'pgsql/currency_catalog.sql'),
  ('finance_billing_plan_active_toggle', '', '0002237087400d9613822898abf578bb', 'pgsql/finance_billing_rules.sql'),
  ('finance_case_label', 'p_contract_id bigint', 'f971cdda5fb3c4ca72b5cf9366081449', 'pgsql/finance_notifications.sql'),
  ('finance_contract_terminated', '', '0e1e113580dd6196aebb01c79db41146', 'pgsql/finance_billing_rules.sql'),
  ('finance_contract_terminating', '', '3723268d67cfbb9aba2f3a85142b49d8', 'pgsql/finance_billing_rules.sql'),
  ('finance_customer_name', 'p_customer_id bigint, p_contract_id bigint', 'fdd5f8822748e34001ea14692efda093', 'pgsql/finance_notifications.sql'),
  ('finance_customer_suffix', 'p_customer_id bigint, p_contract_id bigint', 'abdc2ddaf5032661fae9c75d5adcb5f5', 'pgsql/finance_notifications.sql'),
  ('finance_date_text', 'p_value timestamp with time zone', 'd1b4649056ea7b21c9ddb40dd27b9d49', 'pgsql/finance_notifications.sql'),
  ('finance_default_member_ids', 'p_contract_id bigint', '7d6de8dd85f4071e5cd54f581375730a', 'pgsql/finance_members.sql'),
  ('finance_fill_bill_now', 'p_row "paymentRequests"', '7704cb4d76489f4256be834db9b21e36', 'pgsql/finance_billing_rules.sql'),
  ('finance_fill_manual_unit', 'p_row "paymentRequests"', '8739a36b51b1bd46344150cac7eb0aae', 'pgsql/finance_billing_rules.sql'),
  ('finance_fill_request_stub', '', 'e90d2ed0b8c75ebf96c2d469c02a0fa7', 'pgsql/finance_billing_rules.sql'),
  ('finance_fill_termination_settlement', 'p_row "paymentRequests"', '2a31fa9a22e8b07f03febfda3a26cf99', 'pgsql/finance_billing_rules.sql'),
  ('finance_invoice_derive', '', 'c163403694388ae7a278851fff2f9aed', 'pgsql/finance_foundation.sql'),
  ('finance_invoice_link_rollup', '', 'e17250b5a4b0f1b5648f799262da6f71', 'pgsql/finance_foundation.sql'),
  ('finance_invoice_member_ids', 'p_request_id bigint, p_contract_id bigint', '630088b34159e7e32e01efc258c064ec', 'pgsql/finance_members.sql'),
  ('finance_invoice_paid', 'p_invoice_id bigint', 'dfbf5eed6c485da41a4b88d6c42ccf52', 'pgsql/finance_foundation.sql'),
  ('finance_is_received', 'p_status text', '375c8a24a3de420b43e77393a846ae51', 'pgsql/contract_payment_status_workflow.sql'),
  ('finance_link_members', 'p_table text, p_fk text, p_id bigint, p_lawyer_ids bigint[]', '543cfe83cb043a580d1a56ead158ec85', 'pgsql/finance_members.sql'),
  ('finance_local_date', 'p_ts timestamp with time zone', '2192adb56e61f902b28b54e851a2cc7e', 'pgsql/finance_foundation.sql'),
  ('finance_members_backfill', '', '023efcf65e014d1aa9724a4ac01457e0', 'pgsql/finance_members.sql'),
  ('finance_members_on_invoice_insert', '', '31e69cf12322c50e2dd2e5dc31ce0f30', 'pgsql/finance_members.sql'),
  ('finance_members_on_payment_insert', '', '566e2723d20a8d74d27db1363ec8011d', 'pgsql/finance_members.sql'),
  ('finance_members_on_request_insert', '', '8fca783ab86e914a834418b95a105c8f', 'pgsql/finance_members.sql'),
  ('finance_notifications_prepare', 'p_entities text[], p_limit integer', '69b6de6498afde88cd3c2260b500241a', 'pgsql/finance_notifications.sql'),
  ('finance_notifications_take', 'p_limit integer, p_entities text[]', 'bf3cb4bd7bee1f3b6b9cc1b0ba919f31', 'pgsql/finance_notifications.sql'),
  ('finance_notify_billing_plan', '', '672c634cb30a9ec30c768a796993ee12', 'pgsql/finance_notifications.sql'),
  ('finance_notify_contract', '', 'f5b5bde2bbbf57c06ed9f92b997e3b76', 'pgsql/finance_notifications.sql'),
  ('finance_notify_enqueue', 'p_event text, p_entity text, p_id bigint', '9d42c208e4531d1cc263184b8a9166fd', 'pgsql/finance_notifications.sql'),
  ('finance_notify_invoice', '', 'd4b4bf5f91a35dfb44db52763edd3c6c', 'pgsql/finance_notifications.sql'),
  ('finance_notify_payment', '', '2d0819ccdc6658ac2dd35a24eff820ff', 'pgsql/finance_notifications.sql'),
  ('finance_notify_payment_request', '', '1c39676334702b0171ca4ccc2825604d', 'pgsql/finance_notifications.sql'),
  ('finance_payment_base_amount', 'p_amount double precision, p_rate double precision', '1b8e0e5ddef889d3a37f75e276b7e442', 'pgsql/contract_payment_status_workflow.sql'),
  ('finance_payment_member_ids', 'p_invoice_id bigint, p_request_id bigint, p_contract_id bigint', '64b0a58a0c9478741173136d0d72a581', 'pgsql/finance_members.sql'),
  ('finance_payment_request_cancel_guard', '', '2cdab2ad5b41b4e1fb06813416e25f85', 'pgsql/finance_billing_rules.sql'),
  ('finance_payment_request_derive', '', 'e72b08a3c81fc3d85d0583f54cf55642', 'pgsql/finance_foundation.sql'),
  ('finance_payment_rollup', '', 'bf85324a62a1a3675955954f0a7cfe05', 'pgsql/finance_foundation.sql'),
  ('finance_payment_vnd', 'p_row jsonb', 'f762072b97b1e8f3707748e62fefe389', 'pgsql/contract_payment_status_workflow.sql'),
  ('finance_pr_paid', 'p_pr_id bigint', '6d5a7e126a5552da81512a0e935b1a34', 'pgsql/finance_foundation.sql'),
  ('finance_refresh_overdue', '', 'ffa993106a640421c448bd4814532b02', 'pgsql/finance_foundation.sql'),
  ('finance_request_contract_id', 'p_request_id bigint', '1c57a43cf8895559775bc3f056b39c50', 'pgsql/finance_members.sql'),
  ('finance_request_member_ids', 'p_request_id bigint', '7732f129aa6a839ebfe0084f4a35f8eb', 'pgsql/finance_members.sql'),
  ('finance_today', '', '70d42e3ec956840f6090103a0e1a9759', 'pgsql/finance_foundation.sql'),
  ('finance_vnd_text', 'p_amount numeric', '02c9a3dea4b5ce09dc792914f6cc8aed', 'pgsql/finance_notifications.sql'),
  ('money_allocate_by', 'p_total numeric, p_pr_id bigint, p_contract_id bigint', '3e3e6dc525bfaff5e6d6808b5e1d96dc', 'pgsql/money_flow_trail.sql'),
  ('money_backfill_contract', 'p_contract_id bigint', 'f49008f2061f9c2b6e5b0cc96b39ae38', 'pgsql/money_flow_foundation.sql'),
  ('money_backfill_line_rate', 'p_table text, p_row jsonb, OUT rate numeric, OUT rate_date date', '5cda080f71b53b50a6c5e52043710024', 'pgsql/money_flow_foundation.sql'),
  ('money_backfill_run', '', '73243c837a9e1fcea2a45f301bc985f1', 'pgsql/money_flow_foundation.sql'),
  ('money_base_currency_id', '', 'e2e57483cfa5a2b9bbe4df23712a8566', 'pgsql/money_flow_foundation.sql'),
  ('money_catalog_refresh', 'p_currency_id bigint', 'e0b1776a17a6f7da4bfe22f78ffe8202', 'pgsql/currency_catalog.sql'),
  ('money_catalog_vnd', '', '4fed4971bbaf8f72e405ff366f80578c', 'pgsql/currency_catalog.sql'),
  ('money_company_price_currency', 'p_price numeric, p_service_currency bigint, p_service_price numeric', '8475473b51626668cb242189ad0f039a', 'pgsql/currency_catalog.sql'),
  ('money_contract_billing_locked', 'p_contract_id bigint', 'da073d9d035834ac235ce6ad5c5403b1', 'pgsql/money_flow_foundation.sql'),
  ('money_contract_header', '', 'c034b49e67acf2b8b3880c83e323e3b6', 'pgsql/money_flow_foundation.sql'),
  ('money_contract_service_values', 'p_contract_id bigint', 'd05dbdb96d71a4dccea5b2c5e9249b83', 'pgsql/money_flow_trail.sql'),
  ('money_contract_signed', '', 'dde87b0cf223b59513b823f6cbd76d17', 'pgsql/money_flow_foundation.sql'),
  ('money_contract_total_changed', '', '36e4559a1d8b4bf0a51a30ecdb09e89e', 'pgsql/money_flow_foundation.sql'),
  ('money_currency_code', 'p_currency_id bigint', 'e5ebd188297f5255238da98a264f77b0', 'pgsql/money_flow_foundation.sql'),
  ('money_decimals', 'p_currency_id bigint', 'b9c3550f9f96574234a874f9ed3f35ae', 'pgsql/money_flow_foundation.sql'),
  ('money_exchange_rate_changed', '', '67aa2894e078d3d1db8621af5f1e5b85', 'pgsql/currency_catalog.sql'),
  ('money_exchange_rate_guard', '', 'e7ea1b9b0c5223ed3c9c4bf51dd2b49b', 'pgsql/currency_catalog.sql'),
  ('money_is_base', 'p_currency_id bigint', '54faf2aad4d626c0ddc6de351805f7d1', 'pgsql/money_flow_foundation.sql'),
  ('money_latest_rate', 'p_currency_id bigint, OUT rate numeric, OUT rate_date date', 'c6f7243615ea65339b9f78fb491f1def', 'pgsql/currency_catalog.sql'),
  ('money_line_active', 'p_status text', 'cead7360a946df5a14828af45bf9d70d', 'pgsql/money_flow_foundation.sql'),
  ('money_line_after', '', '281584337fbeaa5c0963b1df86f6a5c2', 'pgsql/money_flow_foundation.sql'),
  ('money_line_amounts', 'p_base_price numeric, p_quantity numeric, p_vat numeric, p_decimals integer, p_rate numeric, OUT sub_native numeric, OUT vat_native numeric, OUT total_native numeric, OUT sub_vnd numeric, OUT vat_vnd numeric, OUT total_vnd numeric', '5a2333bcc0f8b6bb838b48ec093da738', 'pgsql/money_flow_foundation.sql'),
  ('money_line_compute', '', '96d84b677c75628e0320c7eb0a43b613', 'pgsql/money_flow_foundation.sql'),
  ('money_line_contract_id', 'p_table text, p_row jsonb', 'a097015daae7c5a49ad358ede6119511', 'pgsql/money_flow_foundation.sql'),
  ('money_line_currency_unknown', 'p_table text, p_row jsonb', '0c79c7b102cd2a699e3103bffe0bc4d9', 'pgsql/money_flow_foundation.sql'),
  ('money_line_doc_currency', 'p_table text, p_row jsonb', '5fb692cfd1a82117f94d44e8f5386ffb', 'pgsql/money_flow_foundation.sql'),
  ('money_line_document', 'p_table text, p_row jsonb, OUT document_type text, OUT document_id bigint', 'cb18c84c00d6e9da6b3f120f7b0edac1', 'pgsql/service_thread_sync.sql'),
  ('money_line_priced', 'p_row jsonb', 'ea87fee040751eff7a24dca3a5ba8ae4', 'pgsql/money_flow_foundation.sql'),
  ('money_line_rate', 'p_table text, p_row jsonb, OUT rate numeric, OUT rate_date date', '1d6f3d920c5ee3c7376cfb295fc8d4f5', 'pgsql/money_flow_foundation.sql'),
  ('money_line_settled', 'p_row jsonb', 'f5f39149ac70d84021f293b6753b793e', 'pgsql/money_flow_foundation.sql'),
  ('money_line_task_ids', 'p_table text, p_id bigint', '3a79d65ba1cbcfe1cdb463898bd24c74', 'pgsql/service_thread_sync.sql'),
  ('money_line_totals', 'p_lines text, p_parent_id bigint, OUT sub numeric, OUT vat numeric, OUT total numeric', '501ed2c3b3010811216b8e1ab3fbeb02', 'pgsql/money_flow_foundation.sql'),
  ('money_local_date', 'p_ts timestamp with time zone', '2192adb56e61f902b28b54e851a2cc7e', 'pgsql/money_flow_foundation.sql'),
  ('money_payment_request_allocation', 'p_pr_id bigint', '39a86f9cac613c38ca56d73fde40a5ab', 'pgsql/money_flow_trail.sql'),
  ('money_payment_request_billed', 'p_pr_id bigint', '44eef8ba0142a5d0f632dc82042d40e4', 'pgsql/money_flow_foundation.sql'),
  ('money_project_header', '', '24df583820e1c55679c050729310fff5', 'pgsql/money_flow_foundation.sql'),
  ('money_quotation_header', '', '050d3b042b176f5d700952dfa67dbaa3', 'pgsql/money_flow_foundation.sql'),
  ('money_rate_frozen', 'p_rate numeric, p_rate_date date, p_currency_id bigint', 'e13448e8909c4f5f8ca6ff4ff6eb236b', 'pgsql/money_flow_foundation.sql'),
  ('money_rate_to_base', 'p_currency_id bigint, p_on date, OUT rate numeric, OUT rate_date date', '880907c0b82200bb365ccab8aba61d90', 'pgsql/money_flow_foundation.sql'),
  ('money_rate_usable', 'p_status text', '4f8db8acf92f8a0cffa7f51f73a56244', 'pgsql/money_flow_foundation.sql'),
  ('money_refresh_schedule', 'p_contract_id bigint', '58c7caa60f8d0f80fcc97306d4d7786a', 'pgsql/money_flow_foundation.sql'),
  ('money_row_rate_frozen', 'p_row jsonb', '478614650a9b55d4f3f9b2d84c5f95f0', 'pgsql/money_flow_foundation.sql'),
  ('money_schedule_changed', '', 'a3ef7ef3cac80b1f244496f7124eeb24', 'pgsql/money_flow_foundation.sql'),
  ('money_schedule_row_locked', 'p_schedule_id bigint', '93e0346a23f5131613999c4f936b8e6c', 'pgsql/money_flow_foundation.sql'),
  ('money_service_amount_changed', '', '1d321ec5e6d7c4491cf36c4d878136cc', 'pgsql/service_thread_sync.sql'),
  ('money_service_requests_refresh', 'p_project_service_id bigint, p_contract_service_id bigint', '4abe88439293bc466b245a09bf54633f', 'pgsql/service_thread_sync.sql'),
  ('money_split', 'p_total numeric, p_weights numeric[], p_decimals integer', '026067f476e0169c29a848a225a169a1', 'pgsql/money_flow_foundation.sql'),
  ('money_task_has_progress', 'p_task_id bigint, p_created timestamp with time zone, p_status text', '9062885a6897f9fad68b4b4a5b7cc341', 'pgsql/service_thread_sync.sql'),
  ('money_thread_after', '', 'dcfda39ddfec398d48ceb84aa2784b05', 'pgsql/service_thread_sync.sql'),
  ('money_thread_apply', 'p_table text, p_id bigint, p_patch jsonb', 'f8a32694599f8ab3246de8f33efa408f', 'pgsql/service_thread_sync.sql'),
  ('money_thread_before', '', 'b41b0a658c3260ddef043e9fa3092cbd', 'pgsql/service_thread_sync.sql'),
  ('money_thread_billed_contract', 'p_thread bigint, p_extra_contract bigint', '9a5882169203c53afa769801b0df8c6e', 'pgsql/service_thread_sync.sql'),
  ('money_thread_column', 'p_table text, p_field text', '736b8feb8fa002528191d4d34c49e45b', 'pgsql/service_thread_sync.sql'),
  ('money_thread_content', 'p_table text, p_row jsonb', '363f8be46cf1bc33e56382f538e94fe3', 'pgsql/service_thread_sync.sql'),
  ('money_thread_delete_dependents', 'p_table text, p_id bigint', '1138a29460565e3d088c5af54cfcffd5', 'pgsql/service_thread_sync.sql'),
  ('money_thread_diff', 'p_from_table text, p_from jsonb, p_to_table text, p_to jsonb', '6e42ad8f76534395132aacf72705e23b', 'pgsql/service_thread_sync.sql'),
  ('money_thread_is_package', 'p_row jsonb', 'd6377bf83aaeaa45115fcc089f1a91c1', 'pgsql/service_thread_sync.sql'),
  ('money_thread_lines', 'p_thread bigint', 'de2f064ebe7ad9ded8fe91fc69399b33', 'pgsql/service_thread_sync.sql'),
  ('money_thread_links_changed', 'p_table text, p_new jsonb, p_old jsonb', '8ea78108fb699a3390e28c08027a2e12', 'pgsql/service_thread_sync.sql'),
  ('money_thread_log', 'p_action text, p_table text, p_row jsonb, p_field text, p_old text, p_new text, p_origin bigint, p_user bigint', '4aa5fcbb5f38b947112335c8915c7edd', 'pgsql/service_thread_sync.sql'),
  ('money_thread_of_link', 'p_table text, p_row jsonb', 'e8a428b0fac0507188db87ae2dd0c106', 'pgsql/service_thread_sync.sql'),
  ('money_thread_table_order', 'p_table text', '05f77728463b89685fe7e3792ce246ca', 'pgsql/service_thread_sync.sql'),
  ('money_thread_task_in_progress', 'p_table text, p_id bigint, p_thread bigint', 'f972e7e05916c319b3caee40c1909fba', 'pgsql/service_thread_sync.sql'),
  ('money_thread_text', 'p_text text', 'd05c03045ce00643baff7756d3c841e5', 'pgsql/service_thread_sync.sql'),
  ('money_touch_header', 'p_table text, p_id bigint', '65fc6d7f81e0bd42beba94fb75c7d339', 'pgsql/money_flow_foundation.sql'),
  ('money_zero_header_if_empty', 'p_lines text, p_parent_id bigint', '68fd484b2c029c8f23d32b5a5a36dde7', 'pgsql/money_flow_foundation.sql'),
  ('retainer_billing_run_due', '', '3b88ca7752775649c5e2b5f2b1a93435', 'pgsql/retainer_billing_run_due.sql'),
  ('retainer_cycle_amount', 'p_total double precision, p_cycles integer, p_period integer', 'd20eb3bdb2bf173249af043578554d2f', 'pgsql/finance_billing_rules.sql'),
  ('retainer_period_date', 'p_plan "contractBillingPlans", p_period integer', '7168776ca421bf8555b478838f7243d9', 'pgsql/finance_retainer_schedule.sql'),
  ('retainer_schedule_on_plan_change', '', 'fdb4e3e72dd8b70b21d961b0ebc1a5d2', 'pgsql/finance_retainer_schedule.sql'),
  ('retainer_schedule_sync', 'p_plan_id bigint', '021a13d0e4b40716c269d97429859a13', 'pgsql/finance_retainer_schedule.sql'),
  ('retainer_step', 'p_unit text', '0ce78ff2378491342d433c648a328f30', 'pgsql/finance_billing_rules.sql'),
  ('service_thread_backfill_run', '', '1bba1941b9e509512d6ee04a6c9a5535', 'pgsql/service_thread_sync.sql');
CREATE TEMP TABLE _exp_trg (tbl text, name text, fn text, file text);
INSERT INTO _exp_trg VALUES
  ('companyServices', 'trg_money_catalog_vnd', 'money_catalog_vnd', 'pgsql/currency_catalog.sql'),
  ('contractBillingPlans', 'trg_contract_billing_plan_init_retainer_state', 'contract_billing_plan_init_retainer_state', 'pgsql/contract_billing_plans_trigger.sql'),
  ('contractBillingPlans', 'trg_finance_billing_plan_active_toggle', 'finance_billing_plan_active_toggle', 'pgsql/finance_billing_rules.sql'),
  ('contractBillingPlans', 'trg_finance_notify_billing_plan', 'finance_notify_billing_plan', 'pgsql/finance_notifications.sql'),
  ('contractBillingPlans', 'trg_retainer_schedule_on_plan_change', 'retainer_schedule_on_plan_change', 'pgsql/finance_retainer_schedule.sql'),
  ('contractPaymentScheduleServices', 'trg_by_case_schedule_tag_copies_to_payment_request', 'by_case_schedule_tag_copies_to_payment_request', 'pgsql/unified_contract_payment_schedule.sql'),
  ('contractPaymentSchedules', 'trg_by_case_schedule_row_creates_payment_request', 'by_case_schedule_row_creates_payment_request', 'pgsql/unified_contract_payment_schedule.sql'),
  ('contractPaymentSchedules', 'trg_money_schedule_changed', 'money_schedule_changed', 'pgsql/money_flow_foundation.sql'),
  ('contractServices', 'trg_money_a_thread_before', 'money_thread_before', 'pgsql/service_thread_sync.sql'),
  ('contractServices', 'trg_money_line_after', 'money_line_after', 'pgsql/money_flow_foundation.sql'),
  ('contractServices', 'trg_money_line_compute', 'money_line_compute', 'pgsql/money_flow_foundation.sql'),
  ('contractServices', 'trg_money_service_amount_changed', 'money_service_amount_changed', 'pgsql/service_thread_sync.sql'),
  ('contractServices', 'trg_money_thread_after', 'money_thread_after', 'pgsql/service_thread_sync.sql'),
  ('contracts', 'trg_contract_cascade_case_status', 'cascade_payment_status_to_case', 'pgsql/contract_payment_status_workflow.sql'),
  ('contracts', 'trg_contract_init_outstanding', 'contract_init_outstanding', 'pgsql/contract_payment_status_workflow.sql'),
  ('contracts', 'trg_finance_contract_terminated', 'finance_contract_terminated', 'pgsql/finance_billing_rules.sql'),
  ('contracts', 'trg_finance_contract_terminating', 'finance_contract_terminating', 'pgsql/finance_billing_rules.sql'),
  ('contracts', 'trg_finance_notify_contract', 'finance_notify_contract', 'pgsql/finance_notifications.sql'),
  ('contracts', 'trg_money_contract_header', 'money_contract_header', 'pgsql/money_flow_foundation.sql'),
  ('contracts', 'trg_money_contract_signed', 'money_contract_signed', 'pgsql/money_flow_foundation.sql'),
  ('contracts', 'trg_money_contract_total_changed', 'money_contract_total_changed', 'pgsql/money_flow_foundation.sql'),
  ('exchangeRates', 'trg_money_exchange_rate_changed', 'money_exchange_rate_changed', 'pgsql/currency_catalog.sql'),
  ('exchangeRates', 'trg_money_exchange_rate_guard', 'money_exchange_rate_guard', 'pgsql/currency_catalog.sql'),
  ('invoices', 'trg_finance_invoice_derive', 'finance_invoice_derive', 'pgsql/finance_foundation.sql'),
  ('invoices', 'trg_finance_invoice_link_rollup', 'finance_invoice_link_rollup', 'pgsql/finance_foundation.sql'),
  ('invoices', 'trg_finance_members_on_invoice_insert', 'finance_members_on_invoice_insert', 'pgsql/finance_members.sql'),
  ('invoices', 'trg_finance_notify_invoice', 'finance_notify_invoice', 'pgsql/finance_notifications.sql'),
  ('paymentRequests', 'trg_by_case_due_date_activates_payment_request', 'by_case_due_date_activates_payment_request', 'pgsql/by_case_payment_request_automation.sql'),
  ('paymentRequests', 'trg_finance_fill_request_stub', 'finance_fill_request_stub', 'pgsql/finance_billing_rules.sql'),
  ('paymentRequests', 'trg_finance_members_on_request_insert', 'finance_members_on_request_insert', 'pgsql/finance_members.sql'),
  ('paymentRequests', 'trg_finance_notify_payment_request', 'finance_notify_payment_request', 'pgsql/finance_notifications.sql'),
  ('paymentRequests', 'trg_finance_payment_request_cancel_guard', 'finance_payment_request_cancel_guard', 'pgsql/finance_billing_rules.sql'),
  ('paymentRequests', 'trg_finance_payment_request_derive', 'finance_payment_request_derive', 'pgsql/finance_foundation.sql'),
  ('payments', 'trg_finance_members_on_payment_insert', 'finance_members_on_payment_insert', 'pgsql/finance_members.sql'),
  ('payments', 'trg_finance_notify_payment', 'finance_notify_payment', 'pgsql/finance_notifications.sql'),
  ('payments', 'trg_finance_payment_rollup', 'finance_payment_rollup', 'pgsql/finance_foundation.sql'),
  ('payments', 'trg_payment_recompute_contract', 'contract_recompute_outstanding', 'pgsql/contract_payment_status_workflow.sql'),
  ('projectServices', 'trg_money_a_thread_before', 'money_thread_before', 'pgsql/service_thread_sync.sql'),
  ('projectServices', 'trg_money_line_after', 'money_line_after', 'pgsql/money_flow_foundation.sql'),
  ('projectServices', 'trg_money_line_compute', 'money_line_compute', 'pgsql/money_flow_foundation.sql'),
  ('projectServices', 'trg_money_service_amount_changed', 'money_service_amount_changed', 'pgsql/service_thread_sync.sql'),
  ('projectServices', 'trg_money_thread_after', 'money_thread_after', 'pgsql/service_thread_sync.sql'),
  ('projects', 'trg_by_case_case_done_activates_payment_request', 'by_case_case_done_activates_payment_request', 'pgsql/by_case_payment_request_automation.sql'),
  ('projects', 'trg_by_case_one_time_case_linked_creates_payment_request', 'by_case_one_time_case_linked_creates_payment_request', 'pgsql/unified_contract_payment_schedule.sql'),
  ('projects', 'trg_by_service_contract_linked_catches_up_done_tasks', 'by_service_contract_linked_catches_up_done_tasks', 'pgsql/unified_contract_payment_schedule.sql'),
  ('projects', 'trg_money_project_header', 'money_project_header', 'pgsql/money_flow_foundation.sql'),
  ('quotationServices', 'trg_money_a_thread_before', 'money_thread_before', 'pgsql/service_thread_sync.sql'),
  ('quotationServices', 'trg_money_line_after', 'money_line_after', 'pgsql/money_flow_foundation.sql'),
  ('quotationServices', 'trg_money_line_compute', 'money_line_compute', 'pgsql/money_flow_foundation.sql'),
  ('quotationServices', 'trg_money_thread_after', 'money_thread_after', 'pgsql/service_thread_sync.sql'),
  ('quotations', 'trg_money_quotation_header', 'money_quotation_header', 'pgsql/money_flow_foundation.sql'),
  ('serviceComboItems', 'trg_money_catalog_vnd', 'money_catalog_vnd', 'pgsql/currency_catalog.sql'),
  ('serviceCombos', 'trg_money_catalog_vnd', 'money_catalog_vnd', 'pgsql/currency_catalog.sql'),
  ('services', 'trg_money_catalog_vnd', 'money_catalog_vnd', 'pgsql/currency_catalog.sql'),
  ('tasks', 'trg_by_case_task_deleted_rechecks_payment_request', 'by_case_task_deleted_rechecks_payment_request', 'pgsql/by_case_payment_request_automation.sql'),
  ('tasks', 'trg_by_case_task_done_activates_payment_request', 'by_case_task_done_activates_payment_request', 'pgsql/by_case_payment_request_automation.sql'),
  ('tasks', 'trg_by_case_task_linked_activates_payment_request', 'by_case_task_linked_activates_payment_request', 'pgsql/by_case_payment_request_automation.sql'),
  ('tasks', 'trg_by_service_task_group_done_creates_payment_request', 'by_service_task_group_done_creates_payment_request', 'pgsql/unified_contract_payment_schedule.sql'),
  ('tasks', 'trg_case_auto_complete_when_tasks_done', 'case_auto_complete_when_tasks_done', 'pgsql/contract_payment_status_workflow.sql');
CREATE TEMP TABLE _exp_obj (kind text, name text, tbl text, file text, ncols int);
INSERT INTO _exp_obj VALUES
  ('table', 'financeNotificationEvents', NULL, 'pgsql/finance_notifications.sql', NULL),
  ('table', 'serviceChangeLogs', NULL, 'pgsql/service_thread_sync.sql', NULL),
  ('view', 'money_backfill_preview', NULL, 'pgsql/money_flow_foundation.sql', NULL),
  ('view', 'money_backfill_totals_preview', NULL, 'pgsql/money_flow_foundation.sql', NULL),
  ('view', 'money_pr_allocations', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'money_invoice_allocations', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'money_payment_allocations', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'finance_service_money_trail', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'finance_contract_retainer_trail', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'finance_unallocated_money', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'money_consistency_violations', NULL, 'pgsql/money_flow_trail.sql', NULL),
  ('view', 'service_thread_violations', NULL, 'pgsql/service_thread_sync.sql', NULL),
  ('view', 'money_rate_warnings', NULL, 'pgsql/currency_catalog.sql', NULL),
  ('index', 'ux_payment_requests_schedule_open', 'paymentRequests', 'pgsql/finance_foundation.sql', 2),
  ('index', 'ux_payment_requests_project_service_open', 'paymentRequests', 'pgsql/finance_foundation.sql', 2),
  ('index', 'ux_payment_requests_plan_cycle_open', 'paymentRequests', 'pgsql/finance_foundation.sql', 2),
  ('index', 'ix_finance_notification_events_open', 'financeNotificationEvents', 'pgsql/finance_notifications.sql', 1),
  ('index', 'quotationServices_serviceThreadId', 'quotationServices', 'pgsql/service_thread_sync.sql', 1),
  ('index', 'contractServices_serviceThreadId', 'contractServices', 'pgsql/service_thread_sync.sql', 1),
  ('index', 'projectServices_serviceThreadId', 'projectServices', 'pgsql/service_thread_sync.sql', 1),
  ('index', 'contractServices_projectServiceId_unique', 'contractServices', 'pgsql/service_thread_sync.sql', 2),
  ('index', 'serviceChangeLogs_thread', 'serviceChangeLogs', 'pgsql/service_thread_sync.sql', 1),
  ('index', 'serviceChangeLogs_document', 'serviceChangeLogs', 'pgsql/service_thread_sync.sql', 2),
  ('index', 'companyServices_currencyId', 'companyServices', 'pgsql/currency_catalog.sql', 1),
  ('column', 'outStandingAmount', 'contracts', 'pgsql/contract_payment_status_workflow.sql', NULL),
  ('column', 'paymentStatus', 'contracts', 'pgsql/contract_payment_status_workflow.sql', NULL),
  ('column', 'paymentStatus', 'projects', 'pgsql/contract_payment_status_workflow.sql', NULL),
  ('column', 'paidAmount', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'outstandingAmount', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'overdueSince', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'overdueNotifiedAt', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'billingPlanId', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'cycleNo', 'paymentRequests', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'overdueSince', 'invoices', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'overdueNotifiedAt', 'invoices', 'pgsql/finance_foundation.sql', NULL),
  ('column', 'cancelReason', 'paymentRequests', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'cancelledAt', 'paymentRequests', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'isBillingActive', 'contractBillingPlans', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'pausedAt', 'contractBillingPlans', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'pauseReason', 'contractBillingPlans', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'resumeOn', 'contractBillingPlans', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'terminationDate', 'contracts', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'terminationReason', 'contracts', 'pgsql/finance_billing_rules.sql', NULL),
  ('column', 'exchangeRateToBase', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'exchangeRateDate', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'subTotalNative', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'vatAmountNative', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'totalAmountNative', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'basePriceVnd', 'quotationServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'exchangeRateToBase', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'exchangeRateDate', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'subTotalNative', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'vatAmountNative', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'totalAmountNative', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'basePriceVnd', 'contractServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'exchangeRateToBase', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'exchangeRateDate', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'subTotalNative', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'vatAmountNative', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'totalAmountNative', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'basePriceVnd', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'quotationServiceId', 'projectServices', 'pgsql/money_flow_foundation.sql', NULL),
  ('column', 'serviceThreadId', 'quotationServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'serviceType', 'quotationServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'description', 'quotationServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'quantity', 'quotationServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'serviceThreadId', 'contractServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'serviceType', 'contractServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'description', 'contractServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'serviceThreadId', 'projectServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'serviceType', 'projectServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'description', 'projectServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'quantity', 'projectServices', 'pgsql/service_thread_sync.sql', NULL),
  ('column', 'currencyId', 'companyServices', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'basePriceVnd', 'services', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateToBase', 'services', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateDate', 'services', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'priceVnd', 'companyServices', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateToBase', 'companyServices', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateDate', 'companyServices', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'priceVnd', 'serviceComboItems', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateToBase', 'serviceComboItems', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateDate', 'serviceComboItems', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'packageSubTotalVnd', 'serviceCombos', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'totalAmountVnd', 'serviceCombos', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateToBase', 'serviceCombos', 'pgsql/currency_catalog.sql', NULL),
  ('column', 'exchangeRateDate', 'serviceCombos', 'pgsql/currency_catalog.sql', NULL);
CREATE TEMP TABLE _exp_field (coll text, name text, script text);
INSERT INTO _exp_field VALUES
  ('quotationServices', 'exchangeRateToBase', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'exchangeRateDate', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'subTotalNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'vatAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'totalAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'basePriceVnd', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'exchangeRateToBase', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'exchangeRateDate', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'subTotalNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'vatAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'totalAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('contractServices', 'basePriceVnd', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'exchangeRateToBase', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'exchangeRateDate', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'subTotalNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'vatAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'totalAmountNative', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', 'basePriceVnd', 'JsField/RegisterMoneyFlowFields.js'),
  ('projectServices', '@belongsTo:quotationServiceId', 'JsField/RegisterMoneyFlowFields.js'),
  ('quotationServices', 'serviceThreadId', 'JsField/RegisterServiceThreadFields.js'),
  ('contractServices', 'serviceThreadId', 'JsField/RegisterServiceThreadFields.js'),
  ('projectServices', 'serviceThreadId', 'JsField/RegisterServiceThreadFields.js'),
  ('contractServices', 'serviceType', 'JsField/RegisterServiceThreadFields.js'),
  ('projectServices', 'quantity', 'JsField/RegisterServiceThreadFields.js'),
  ('@collection', 'serviceChangeLogs', 'JsField/RegisterServiceThreadFields.js'),
  ('companyServices', 'currency', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('services', 'basePriceVnd', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('services', 'exchangeRateToBase', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('services', 'exchangeRateDate', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('companyServices', 'priceVnd', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('companyServices', 'exchangeRateToBase', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('companyServices', 'exchangeRateDate', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceComboItems', 'priceVnd', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceComboItems', 'exchangeRateToBase', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceComboItems', 'exchangeRateDate', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceCombos', 'packageSubTotalVnd', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceCombos', 'totalAmountVnd', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceCombos', 'exchangeRateToBase', 'JsField/RegisterCompanyServiceCurrency.js'),
  ('serviceCombos', 'exchangeRateDate', 'JsField/RegisterCompanyServiceCurrency.js');
CREATE TEMP TABLE _exp_js (file text, root text, md5 text);
INSERT INTO _exp_js VALUES
  ('All Module/Case/CaseCreateForm.js', 'ProjectCreateForm', '747afe94349dae71689a52780204bb29'),
  ('All Module/Contract/ContractCreateForm.js', 'ContractCreateForm', 'bee52bcd3a318e800aad173672fd609b'),
  ('All Module/Quotation/QuotationCreateForm.js', 'QuotationCreateForm', 'f57bdae617b50c24fb3e995f90a71862'),
  ('All Module/Case/CaseServices.js', 'CaseServices', '1c7d1e7ad0959bf3cb6291173418ec4d'),
  ('All Module/Contract/ContractServices.js', 'ContractServicesBlock', '00911785b87406cc9b7fdc17bb371caa'),
  ('All Module/Quotation/QuotationServices.js', 'QuotationServicesBlock', '6dac9a61279663f9096c828704de1062'),
  ('All Module/Contract/ContractDetailView.js', 'ContractDetailPage', '35e00219a0caae304d15963b5b3de24a'),
  ('All Module/Contract/ContractPaymentScheduleDetailBlock.js', 'PaymentScheduleDetailBlock', 'f39dc17bfa9a2ffaf7c07662d77a920d'),
  ('All Module/Case/CaseFinanceBlock.js', 'CaseFinanceBlock', '2c1dde14d59914aed568bac7c15a2c16'),
  ('All Module/Payment/PaymentContractDetailBlock.js', 'PaymentContractDetailBlock', 'f3b0b229be008b0257890d92f818640e'),
  ('All Module/Payment/PaymentRequestCreateBlock.js', 'PaymentRequestCreateBlock', '9a369ec4b485fd059bd405fb61c06653'),
  ('All Module/Payment/PaymentCreateBlock.js', 'PaymentCreateBlock', 'a648a0918e033f16dd2c93564ae2b718'),
  ('All Module/Invoice/InvoiceCreateBlock.js', 'InvoiceCreateBlock', '8212b6f2ede17163cdd35bfacd9eb070'),
  ('All Module/Service/ServiceChangeLog.js', 'ServiceChangeLog', '2e7e4faa71d052b086140879e99fa56a');

-- ---- body of pgsql/deploy/check_dev_readiness.sql (appended by scripts/deploy/gen-dev-check.js)

-- ---- 1. functions: present, same arguments, same body as the repo
INSERT INTO _check
SELECT 1, 'function', e.name || '(' || e.args || ')',
       CASE WHEN p.prosrc IS NULL AND other.n > 0 THEN 'OUTDATED'
            WHEN p.prosrc IS NULL THEN 'MISSING'
            WHEN md5(p.prosrc) <> e.md5 THEN 'OUTDATED'
            ELSE 'OK' END,
       e.file || CASE WHEN p.prosrc IS NULL AND other.n > 0
                      THEN ' — exists with other arguments: ' || other.args ELSE '' END,
       CASE WHEN p.prosrc IS NOT NULL AND md5(p.prosrc) = e.md5 THEN '' ELSE 'run ' || e.file END
FROM _exp_fn e
LEFT JOIN LATERAL (
  SELECT pp.prosrc FROM pg_proc pp JOIN pg_namespace n ON n.oid = pp.pronamespace
  WHERE n.nspname = 'public' AND pp.proname = e.name AND pg_get_function_identity_arguments(pp.oid) = e.args
  LIMIT 1) p ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS n, string_agg(pg_get_function_identity_arguments(pp.oid), ' | ') AS args
  FROM pg_proc pp JOIN pg_namespace n ON n.oid = pp.pronamespace
  WHERE n.nspname = 'public' AND pp.proname = e.name) other ON true;

-- ---- 2. triggers: on the right table, calling the right function
INSERT INTO _check
SELECT 2, 'trigger', e.tbl || '.' || e.name,
       CASE WHEN t.fn IS NULL THEN 'MISSING' WHEN t.fn <> e.fn THEN 'OUTDATED' ELSE 'OK' END,
       e.file || ' — calls ' || e.fn || '()',
       CASE WHEN t.fn = e.fn THEN '' ELSE 'run ' || e.file END
FROM _exp_trg e
LEFT JOIN LATERAL (
  SELECT f.proname AS fn
  FROM pg_trigger tg
  JOIN pg_class c ON c.oid = tg.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  JOIN pg_proc f ON f.oid = tg.tgfoid
  WHERE c.relname = e.tbl AND tg.tgname = e.name AND NOT tg.tgisinternal
  LIMIT 1) t ON true;

-- ---- 3. tables, views, indexes, columns the files create
-- an index also needs its key column count: an older copy can keep the name
-- (e.g. single-column ux_payment_requests_*, which NocoBase's collection sync drops)
INSERT INTO _check
SELECT 3, e.kind,
       CASE WHEN e.kind IN ('column', 'index') THEN e.tbl || '.' || e.name ELSE e.name END,
       CASE WHEN NOT ok THEN 'MISSING' WHEN outdated THEN 'OUTDATED' ELSE 'OK' END,
       e.file || CASE WHEN outdated THEN format(' — %s key column(s) here, %s expected', found_cols, e.ncols) ELSE '' END,
       CASE WHEN ok AND NOT outdated THEN '' ELSE 'run ' || e.file END
FROM (
  SELECT e.*, x.found_cols,
         COALESCE(e.kind = 'index' AND e.ncols IS NOT NULL AND x.found_cols IS DISTINCT FROM e.ncols, false) AS outdated
  FROM (
    SELECT e.*,
           CASE e.kind
             WHEN 'column' THEN EXISTS (SELECT 1 FROM information_schema.columns ic
                                        WHERE ic.table_schema = 'public' AND ic.table_name = e.tbl AND ic.column_name = e.name)
             ELSE to_regclass(format('public.%I', e.name)) IS NOT NULL
           END AS ok
    FROM _exp_obj e) e
  LEFT JOIN LATERAL (
    SELECT ix.indnatts::int AS found_cols FROM pg_index ix
    WHERE e.kind = 'index' AND e.ok AND ix.indexrelid = to_regclass(format('public.%I', e.name))) x ON true) e;

-- ---- 4. NocoBase field registrations (tables "fields" / "collections")
DO $check$
BEGIN
  IF to_regclass('public.fields') IS NULL OR to_regclass('public.collections') IS NULL THEN
    INSERT INTO _check VALUES (4, 'nocobase field', '(fields / collections)', 'INFO',
      'no NocoBase metadata tables in this database', '');
    RETURN;
  END IF;
  INSERT INTO _check
  SELECT 4, 'nocobase field',
         CASE WHEN e.coll = '@collection' THEN 'collection ' || e.name
              WHEN e.name LIKE '@belongsTo:%' THEN e.coll || ' → relation on ' || substr(e.name, 12)
              ELSE e.coll || '.' || e.name END,
         CASE WHEN e.registered THEN 'OK' ELSE 'MISSING' END,
         e.script,
         CASE WHEN e.registered THEN '' ELSE 'run ' || e.script END
  FROM (
    SELECT e.*,
           CASE WHEN e.coll = '@collection' THEN EXISTS (SELECT 1 FROM collections c WHERE c.name = e.name)
                WHEN e.name LIKE '@belongsTo:%' THEN EXISTS (
                  SELECT 1 FROM fields f WHERE f."collectionName" = e.coll AND f.type = 'belongsTo'
                    AND f.options::jsonb ->> 'foreignKey' = substr(e.name, 12))
                ELSE EXISTS (SELECT 1 FROM fields f WHERE f."collectionName" = e.coll AND f.name = e.name)
           END AS registered -- (not "found": a PL/pgSQL variable)
    FROM _exp_field e) e;
  -- the old companyServices.currencies (a hasMany that wrote into currencies) must be gone
  INSERT INTO _check
  SELECT 4, 'nocobase field', 'companyServices.currencies (old hasMany)', 'EXTRA',
         'JsField/RegisterCompanyServiceCurrency.js removes it', 'run JsField/RegisterCompanyServiceCurrency.js'
  WHERE EXISTS (SELECT 1 FROM fields f WHERE f."collectionName" = 'companyServices' AND f.name = 'currencies' AND f.type = 'hasMany');
END
$check$;

-- ---- 5. JS blocks: every block that renders a repo block, same code or not
DO $check$
BEGIN
  IF to_regclass('public."flowModels"') IS NULL THEN
    INSERT INTO _check VALUES (5, 'js block', '(flowModels)', 'INFO', 'no NocoBase flowModels table in this database', '');
    RETURN;
  END IF;
  INSERT INTO _check
  WITH RECURSIVE m AS (
    SELECT uid, options::jsonb AS o FROM "flowModels"
  ), coded AS (
    SELECT uid, o, o #>> '{stepParams,jsSettings,runJs,code}' AS code
    FROM m WHERE o #>> '{stepParams,jsSettings,runJs,code}' IS NOT NULL
  ), rooted AS (
    SELECT c.uid, c.o, c.code,
           (SELECT r.mt[1]
            FROM regexp_matches(c.code, 'ctx\.render\(\s*(?:React\.createElement\(\s*)?([A-Za-z]+)', 'g')
                 WITH ORDINALITY AS r(mt, i)
            ORDER BY r.i DESC LIMIT 1) AS root
    FROM coded c
  ), blocks AS (
    SELECT r.uid, r.o, r.code, e.file, e.md5
    FROM rooted r JOIN _exp_js e ON e.root = r.root
  ), chain AS (
    SELECT b.uid AS block, b.o ->> 'parentId' AS parent, 0 AS depth FROM blocks b
    UNION ALL
    SELECT ch.block, m.o ->> 'parentId', ch.depth + 1
    FROM chain ch JOIN m ON m.uid = ch.parent
    WHERE ch.depth < 40
  ), orphans AS (
    SELECT DISTINCT ch.block FROM chain ch
    WHERE ch.parent IS NOT NULL AND NOT EXISTS (SELECT 1 FROM m WHERE m.uid = ch.parent)
  )
  SELECT 5, 'js block', b.file || ' · ' || b.uid,
         CASE WHEN o.block IS NOT NULL THEN 'INFO'
              WHEN md5(btrim(replace(b.code, E'\r\n', E'\n'), E' \t\r\n')) = b.md5 THEN 'OK'
              ELSE 'OUTDATED' END,
         CASE WHEN o.block IS NOT NULL THEN 'orphan (its page / popup was deleted): shown nowhere'
              ELSE COALESCE(b.o ->> 'use', '') END,
         CASE WHEN o.block IS NULL AND md5(btrim(replace(b.code, E'\r\n', E'\n'), E' \t\r\n')) <> b.md5
              THEN 're-paste ' || b.file ELSE '' END
  FROM blocks b LEFT JOIN orphans o ON o.block = b.uid;
  -- repo blocks this instance does not use
  INSERT INTO _check
  SELECT 5, 'js block', e.file, 'INFO', 'no block renders ' || e.root || ' here', ''
  FROM _exp_js e
  WHERE NOT EXISTS (SELECT 1 FROM _check c WHERE c.section = 5 AND c.item LIKE e.file || ' · %');
END
$check$;

-- ---- 6. data (information: what the backfills / rates still have to do)
DO $check$
DECLARE
  t text;
  n bigint;
  v record;
BEGIN
  FOREACH t IN ARRAY ARRAY['quotationServices', 'contractServices', 'projectServices'] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = t AND column_name = 'serviceThreadId') THEN
      EXECUTE format('SELECT count(*) FROM %I WHERE "serviceThreadId" IS NULL', t) INTO n;
      INSERT INTO _check VALUES (6, 'data', t || ': lines without a service thread', CASE WHEN n = 0 THEN 'OK' ELSE 'INFO' END,
        n || ' line(s)', CASE WHEN n = 0 THEN '' ELSE 'service_thread_backfill_preview → service_thread_backfill' END);
    END IF;
    IF to_regproc('public.money_line_priced') IS NOT NULL AND to_regproc('public.money_row_rate_frozen') IS NOT NULL
       AND EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public' AND table_name = t AND column_name = 'exchangeRateDate') THEN
      EXECUTE format('SELECT count(*) FROM %I x WHERE money_line_priced(to_jsonb(x)) AND NOT money_row_rate_frozen(to_jsonb(x))', t) INTO n;
      INSERT INTO _check VALUES (6, 'data', t || ': priced lines without a frozen rate', CASE WHEN n = 0 THEN 'OK' ELSE 'INFO' END,
        n || ' line(s)', CASE WHEN n = 0 THEN '' ELSE 'the money backfill (inside service_thread_backfill) prices them' END);
    END IF;
  END LOOP;

  IF to_regclass('public."exchangeRates"') IS NOT NULL AND to_regclass('public.currencies') IS NOT NULL THEN
    SELECT count(*) INTO n
    FROM "exchangeRates" er JOIN currencies tc ON tc.id = er."toCurrencyId"
    WHERE upper(tc.code) <> 'VND';
    INSERT INTO _check VALUES (6, 'data', 'exchange rates entered VND → foreign', CASE WHEN n = 0 THEN 'OK' ELSE 'INFO' END,
      n || ' rate(s)', CASE WHEN n = 0 THEN '' ELSE 'currency_catalog_fix_preview → currency_catalog_fix' END);
    FOR v IN
      SELECT upper(fc.code) AS code, max(er."effectiveDate")::date AS last_day
      FROM "exchangeRates" er
      JOIN currencies fc ON fc.id = er."fromCurrencyId"
      JOIN currencies tc ON tc.id = er."toCurrencyId" AND upper(tc.code) = 'VND'
      GROUP BY upper(fc.code)
    LOOP
      INSERT INTO _check VALUES (6, 'data', 'latest ' || v.code || ' → VND rate',
        CASE WHEN v.last_day >= current_date - 30 THEN 'OK' ELSE 'INFO' END,
        v.last_day || ' (' || (current_date - v.last_day) || ' days ago)',
        CASE WHEN v.last_day >= current_date - 30 THEN '' ELSE 'enter a current rate in Exchange Rates' END);
    END LOOP;
  END IF;

  FOREACH t IN ARRAY ARRAY['money_consistency_violations', 'service_thread_violations', 'money_rate_warnings'] LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('SELECT count(*) FROM %I', t) INTO n;
      INSERT INTO _check VALUES (6, 'data', t, CASE WHEN n = 0 THEN 'OK' ELSE 'INFO' END,
        n || ' row(s)', CASE WHEN n = 0 THEN '' ELSE 'SELECT * FROM ' || t END);
    END IF;
  END LOOP;
END
$check$;

-- ---- 0. summary: what to do, per file / script
INSERT INTO _check
SELECT 0, 'summary', f.file,
       'RUN',
       count(*) || ' item(s) missing or outdated',
       CASE WHEN f.file LIKE 'JsField/%' THEN 'paste in the browser console of an admin page'
            ELSE 'pgAdmin: run the file (runbook step 1 order)' END
FROM (SELECT substr(action, 5) AS file FROM _check WHERE section BETWEEN 1 AND 4 AND action LIKE 'run %') f
GROUP BY f.file;
INSERT INTO _check
SELECT 0, 'summary', substr(action, 10), 'RE-PASTE',
       count(*) || ' block(s): ' || string_agg(split_part(item, ' · ', 2), ' ' ORDER BY item),
       'Edit code of each block, paste the repo file'
FROM _check WHERE section = 5 AND action LIKE 're-paste %'
GROUP BY substr(action, 10);
INSERT INTO _check
SELECT 0, 'summary', '(all SQL objects, fields and blocks)', 'OK', 'nothing to deploy', ''
WHERE NOT EXISTS (SELECT 1 FROM _check WHERE section = 0);

SELECT part, item, status, detail, action
FROM _check
ORDER BY section,
         CASE status WHEN 'RUN' THEN 0 WHEN 'RE-PASTE' THEN 1 WHEN 'MISSING' THEN 2 WHEN 'OUTDATED' THEN 3
                     WHEN 'EXTRA' THEN 4 WHEN 'INFO' THEN 5 ELSE 6 END,
         item;

