-- GENERATED by scripts/tests/sql/gen-money-cases.js from
-- scripts/tests/fixtures/money-cases.json: do not edit; edit the JSON and re-run the generator.
-- The JS preview is tested against the same cases (scripts/tests/money-cases.test.js).
--   bash scripts/tests/sql/run-local.sh pgsql/tests/money_cases_test.sql
-- BEGIN ... ROLLBACK; prints "ALL MONEY CASES PASSED". Ids 997900000000001+.
BEGIN;

INSERT INTO currencies (id, code, "decimalPlaces", "isBaseCurrency")
SELECT 997900000000099, 'VND', 0, true WHERE NOT EXISTS (SELECT 1 FROM currencies WHERE upper(code) = 'VND');
INSERT INTO currencies (id, code, "decimalPlaces") VALUES (997900000000001, 'XTU', 2);
INSERT INTO currencies (id, code, "decimalPlaces") VALUES (997900000000002, 'XTS', 2);
INSERT INTO currencies (id, code, "decimalPlaces") VALUES (997900000000003, 'XTC', 2);
INSERT INTO currencies (id, code, "decimalPlaces") VALUES (997900000000004, 'XTD', 2);
ALTER TABLE "exchangeRates" DISABLE TRIGGER USER;
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000100, 997900000000001, money_base_currency_id(), 26176.5, '2026-08-18T09:18:17Z', NULL);
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000101, 997900000000001, money_base_currency_id(), 25000, '2026-09-01T20:00:00Z', NULL);
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000102, 997900000000001, money_base_currency_id(), 30000, '2026-09-05T03:00:00Z', 'inactive');
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000103, 997900000000001, money_base_currency_id(), 26000, '2026-09-10T03:00:00Z', NULL);
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000104, money_base_currency_id(), 997900000000002, 0.00005, '2026-08-18T08:57:57Z', NULL);
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000105, 997900000000004, money_base_currency_id(), 21000, '2026-09-15T03:00:00Z', NULL);
INSERT INTO "exchangeRates" (id, "fromCurrencyId", "toCurrencyId", rate, "effectiveDate", status) VALUES (997900000000106, 997900000000004, money_base_currency_id(), 22000, '2026-09-15T03:00:00Z', NULL);
ALTER TABLE "exchangeRates" ENABLE TRIGGER USER;

DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(10, 1, 8, 2, 26176.5);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (10::numeric, 0.8::numeric, 10.8::numeric, 261765::numeric, 20941::numeric, 282706::numeric) THEN
    RAISE EXCEPTION 'FAIL line "10 USD + 8%%": got %', a;
  END IF;
END $$;
DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(120.5, 2, 4, 2, 26176.5);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (241::numeric, 9.64::numeric, 250.64::numeric, 6308537::numeric, 252341::numeric, 6560878::numeric) THEN
    RAISE EXCEPTION 'FAIL line "120.50 USD x 2 + 4%%": got %', a;
  END IF;
END $$;
DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(1000, 1, 8, 2, 26176.5);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (1000::numeric, 80::numeric, 1080::numeric, 26176500::numeric, 2094120::numeric, 28270620::numeric) THEN
    RAISE EXCEPTION 'FAIL line "1000 USD + 8%%": got %', a;
  END IF;
END $$;
DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(10, 1, 4, 2, 26000);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (10::numeric, 0.4::numeric, 10.4::numeric, 260000::numeric, 10400::numeric, 270400::numeric) THEN
    RAISE EXCEPTION 'FAIL line "VAT under 5%%": got %', a;
  END IF;
END $$;
DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(200, 1, 10, 2, 20480.471317);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (200::numeric, 20::numeric, 220::numeric, 4096094::numeric, 409609::numeric, 4505703::numeric) THEN
    RAISE EXCEPTION 'FAIL line "200 SGD + 10%%": got %', a;
  END IF;
END $$;
DO $$ DECLARE a RECORD; BEGIN
  SELECT * INTO a FROM money_line_amounts(1000000, 1, 8, 0, 1);
  IF (a.sub_native, a.vat_native, a.total_native, a.sub_vnd, a.vat_vnd, a.total_vnd) IS DISTINCT FROM
     (1000000::numeric, 80000::numeric, 1080000::numeric, 1000000::numeric, 80000::numeric, 1080000::numeric) THEN
    RAISE EXCEPTION 'FAIL line "VND line": got %', a;
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(10000001, ARRAY[30, 30, 40]::numeric[], 0) IS DISTINCT FROM ARRAY[3000000, 3000000, 4000001]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 10000001 by 30/30/40: got %', money_split(10000001, ARRAY[30, 30, 40]::numeric[], 0);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(10000000, ARRAY[33.33, 33.33, 33.34]::numeric[], 0) IS DISTINCT FROM ARRAY[3333000, 3333000, 3334000]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 10000000 by 33.33/33.33/33.34: got %', money_split(10000000, ARRAY[33.33, 33.33, 33.34]::numeric[], 0);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(100, ARRAY[1, 1, 1]::numeric[], 0) IS DISTINCT FROM ARRAY[34, 33, 33]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 100 by 1/1/1: got %', money_split(100, ARRAY[1, 1, 1]::numeric[], 0);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(0.1, ARRAY[1, 1, 1]::numeric[], 2) IS DISTINCT FROM ARRAY[0.04, 0.03, 0.03]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 0.1 by 1/1/1: got %', money_split(0.1, ARRAY[1, 1, 1]::numeric[], 2);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(708480, ARRAY[336960, 1080000]::numeric[], 0) IS DISTINCT FROM ARRAY[168480, 540000]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 708480 by 336960/1080000: got %', money_split(708480, ARRAY[336960, 1080000]::numeric[], 0);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(4000000, ARRAY[30, 40]::numeric[], 0) IS DISTINCT FROM ARRAY[1714286, 2285714]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 4000000 by 30/40: got %', money_split(4000000, ARRAY[30, 40]::numeric[], 0);
  END IF;
END $$;
DO $$ BEGIN
  IF money_split(5, ARRAY[0, 0]::numeric[], 0) IS DISTINCT FROM ARRAY[3, 2]::numeric[] THEN
    RAISE EXCEPTION 'FAIL split 5 by 0/0: got %', money_split(5, ARRAY[0, 0]::numeric[], 0);
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000001, DATE '2026-09-01');
  IF r.rate IS DISTINCT FROM 26176.5::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-08-18' THEN
    RAISE EXCEPTION 'FAIL rate XTU on 2026-09-01: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000001, DATE '2026-09-02');
  IF r.rate IS DISTINCT FROM 25000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-09-02' THEN
    RAISE EXCEPTION 'FAIL rate XTU on 2026-09-02: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000001, DATE '2026-09-07');
  IF r.rate IS DISTINCT FROM 25000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-09-02' THEN
    RAISE EXCEPTION 'FAIL rate XTU on 2026-09-07: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000001, DATE '2026-09-15');
  IF r.rate IS DISTINCT FROM 26000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-09-10' THEN
    RAISE EXCEPTION 'FAIL rate XTU on 2026-09-15: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000001, DATE '2026-08-01');
  IF r.rate IS DISTINCT FROM 26176.5::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-08-18' THEN
    RAISE EXCEPTION 'FAIL rate XTU on 2026-08-01: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000002, DATE '2026-09-01');
  IF r.rate IS DISTINCT FROM 20000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-08-18' THEN
    RAISE EXCEPTION 'FAIL rate XTS on 2026-09-01: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000003, DATE '2026-09-01');
  IF r.rate IS NOT NULL OR false THEN
    RAISE EXCEPTION 'FAIL rate XTC on 2026-09-01: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000004, DATE '2026-09-20');
  IF r.rate IS DISTINCT FROM 22000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-09-15' THEN
    RAISE EXCEPTION 'FAIL rate XTD on 2026-09-20: got %, %', r.rate, r.rate_date;
  END IF;
END $$;
DO $$ DECLARE r RECORD; BEGIN
  SELECT * INTO r FROM money_rate_to_base(997900000000004, DATE '2026-09-01');
  IF r.rate IS DISTINCT FROM 22000::numeric OR r.rate_date IS DISTINCT FROM DATE '2026-09-15' THEN
    RAISE EXCEPTION 'FAIL rate XTD on 2026-09-01: got %, %', r.rate, r.rate_date;
  END IF;
END $$;

DO $$ BEGIN RAISE NOTICE 'ALL MONEY CASES PASSED'; END $$;
ROLLBACK;
