const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// pgsql/deploy/check_dev_readiness.sql is generated by scripts/deploy/gen-dev-check.js
// from the repo: it must be regenerated whenever an input changes.
const root = path.resolve(__dirname, "../..");
const gen = require("../deploy/gen-dev-check");
const OUT = path.join(root, gen.OUTPUT);
assert.ok(fs.existsSync(OUT), `${gen.OUTPUT} missing: run node scripts/deploy/gen-dev-check.js`);
const out = fs.readFileSync(OUT, "utf8");

// stale check: the digest of every input is written in the header
const header = out.match(/^-- inputs-sha256: ([0-9a-f]{64})$/m);
assert.ok(header, "digest header missing");
assert.equal(header[1], gen.inputsDigest(), `${gen.OUTPUT} is stale: run node scripts/deploy/gen-dev-check.js`);

// the JS block fingerprint is the one the SQL computes: CRLF -> LF, outer whitespace trimmed
assert.equal(gen.normalizeCode("\r\n  a\r\nb \n"), "a\nb");
assert.equal(gen.codeMd5("x\r\n"), crypto.createHash("md5").update("x", "utf8").digest("hex"));
for (const block of gen.JS_BLOCKS) {
  const code = fs.readFileSync(path.join(root, block.file), "utf8");
  assert.ok(out.includes(`('${block.file}', '${block.root}', '${gen.codeMd5(code)}')`), `${block.file}: fingerprint not in the check`);
}

// read-only on real data: it only creates / fills session TEMP tables (named _…),
// and its last statement is the result SELECT (pgAdmin shows the last result)
const statements = out.replace(/--[^\n]*/g, "");
assert.doesNotMatch(statements, /\b(UPDATE|DELETE\s+FROM|TRUNCATE|ALTER\s+TABLE|COMMIT|BEGIN\s*;)\b/i, "no writes, no transaction");
for (const m of statements.matchAll(/\bCREATE\s+(\w+\s+)?TABLE\s+(\S+)/gi)) {
  assert.match(m[1] || "", /TEMP/i, `only temp tables are created: ${m[0]}`);
  assert.match(m[2], /^_/, `temp tables are named _…: ${m[0]}`);
}
for (const m of statements.matchAll(/\bINSERT\s+INTO\s+(\S+)/gi)) assert.match(m[1], /^_/, `writes only to temp tables: ${m[0]}`);
assert.match(out.trimEnd(), /SELECT[\s\S]*FROM _check[\s\S]*;$/, "ends with the result SELECT");
// an index is compared by its key column count too: an older single-column copy of a
// NocoBase-safe ("x", "x") index keeps its name, so existence alone would say OK
for (const name of ["ux_payment_requests_schedule_open", "ux_payment_requests_project_service_open", "contractServices_projectServiceId_unique"]) {
  assert.match(out, new RegExp(`\\('index', '${name}', '\\w+', 'pgsql/\\w+\\.sql', 2\\)`), `${name}: expected with 2 key columns`);
}
const body = fs.readFileSync(path.join(root, "scripts/deploy/check-body.sql"), "utf8");
assert.match(body, /indnatts/, "check-body compares index key column counts");
// the sections the design promised
["'function'", "'trigger'", "'index'", "'view'", "'table'", "'column'", "'nocobase field'", "'js block'", "'data'"].forEach((part) =>
  assert.ok(out.includes(part), `section ${part} missing`));
console.log("dev-check: all tests passed");
