-- ============================================================
-- Retainer Billing Automation
-- See docs/superpowers/specs/2026-09-07-retainer-billing-automation-design.md
--
-- SUPERSEDED 2026-09-08 by the contractBillingPlans architecture (see
-- docs/superpowers/specs/2026-09-08-contract-billing-plans-architecture-design.md
-- and pgsql/contract_billing_plans_trigger.sql) — retainer billing state now
-- lives on "contractBillingPlans" rows, not contracts.nextRetainerBillingDate/
-- retainerPeriodsBilled. Those 2 columns, plus contracts.retainerDuration
-- (also read below), were already DROPPED by
-- pgsql/contracts_drop_dead_columns.sql, and this file's own trigger was
-- already dropped by pgsql/contracts_drop_obsolete_retainer_trigger.sql.
--
-- Found 2026-09-22 during a RAM/conflict audit of every pgsql/*.sql file:
-- unlike by_case_payment_request_automation.sql's identical situation (see
-- its own header), THIS file was never updated to stop recreating its
-- trigger — until now, re-running it as originally written would either
-- (a) fail outright at CREATE TRIGGER (columns dropped, so "UPDATE OF
-- ... retainerDuration" has nothing to reference), or, in an environment
-- where the columns hadn't been dropped yet, (b) silently resurrect the
-- exact obsolete trigger that blocked the column drop in the first place.
-- Changed to match by_case_payment_request_automation.sql's own pattern:
-- DROP only, idempotently, never recreated, regardless of run order
-- relative to the other migration files. The function/columns below are
-- kept as comments for history/rollback reference only — not executed.
--
-- Idempotent: every statement in this file is safe to run again on a
-- database that already has some or all of it applied.
-- ============================================================

-- ---- Schema (history only — DO NOT re-add; superseded by contractBillingPlans) --
-- ALTER TABLE contracts ADD COLUMN IF NOT EXISTS "nextRetainerBillingDate" date;
-- ALTER TABLE contracts ADD COLUMN IF NOT EXISTS "retainerPeriodsBilled" integer DEFAULT 0;

-- ---- Trigger (history only): initialize/reset a contract's retainer
-- ---- billing state. Function body kept verbatim in this comment purely
-- ---- for reference — not created; see contract_init_retainer_billing_state's
-- ---- fields (paymentSchedule.retainerRule.enabled, retainerDuration,
-- ---- nextRetainerBillingDate, retainerPeriodsBilled), all superseded.
--
-- CREATE OR REPLACE FUNCTION public.contract_init_retainer_billing_state()
-- RETURNS trigger LANGUAGE plpgsql AS $function$
-- DECLARE
--   v_retainer_rule jsonb; v_enabled boolean; v_duration numeric; v_first_payment date;
-- BEGIN
--   v_retainer_rule := NEW."paymentSchedule" -> 'retainerRule';
--   v_enabled := COALESCE((v_retainer_rule ->> 'enabled')::boolean, false);
--   v_duration := NULLIF(NEW."retainerDuration", 0);
--   IF NOT v_enabled OR v_duration IS NULL THEN
--     NEW."nextRetainerBillingDate" := NULL;
--     RETURN NEW;
--   END IF;
--   IF COALESCE(NEW."retainerPeriodsBilled", 0) = 0 THEN
--     v_first_payment := NULLIF(NEW."paymentSchedule" ->> 'firstPaymentDate', '')::date;
--     NEW."nextRetainerBillingDate" := v_first_payment;
--     NEW."retainerPeriodsBilled" := 0;
--   END IF;
--   RETURN NEW;
-- END;
-- $function$;

DROP TRIGGER IF EXISTS trg_contract_init_retainer_billing_state ON contracts;
DROP FUNCTION IF EXISTS public.contract_init_retainer_billing_state();
